#!/usr/bin/env bash
#
# Copyright (C) 2017-2019 Janek Bevendorff, Webis Group
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

if command -v python3 > /dev/null && [[ $(python3 --version) > "Python 3.5.99" ]]; then
    exec python3 authorship_unmasking/$(basename $0).py "$@"
elif command -v python3.6 > /dev/null; then
    exec python3.6 authorship_unmasking/$(basename $0).py "$@"
else
    echo "Minimum required Python version not satisfied. Need at least Python 3.6." >&2
    exit 1
fi
